### ISSUE TITLE
Tests missing in source tarball on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [hsluv/hsluv-python#29]
Hi! Similar to the missing LICENSE.txt (#28), the tests are also missing in the source tarball on pypi.org.

Tests are fairly important for downstreams (such as Linux distributions), so that they can ensure software integrates with the existing ecosystem (e.g. python interpreters, etc.).
It would be very awesome, if you could add them!

**Comment by hartwork** [comment]
I guess we can either:
- a) add the needed files to Manifest.in
- b) rename folder `tests` to `hsluv_tests` and let setuptools find it using `find_packages`
- c) turn `hsluv.py` into `hsluv/__init__.py`, move `tests/*` to `hsluv/tests/`, and let setuptools find it using `find_packages`

@boronine how do you feel bout these?

PS: I noticed that `python3.8 setup.py sdist` includes the test files on one distribution of Linux already (with setuptools 52.0.0 but not on another (with setuptools 50.3.2). Could use a deeper look, seems like the version of setuptools used in making releases plays a part here.

**Comment by dvzrv** [comment]
Preferably the tests are only included in the sdist, but not in the bdist packages. Personally, I would probably tweak MANIFEST.in, unless one really wants the tests also distributed in the bdist package (in which case b or c applies).

**Comment by boronine** [comment]
Thanks for the help guys. I'm not well versed in Python packaging but a quick Google search confirmed @dvzrv's point above. The MANIFEST.in solution seems most robust so I implemented it in master. 

Both sdist and bdist look good on my end in terms of tests and LICENCE file. If either of you confirm that it looks good on your end too, I will release it as v5.0.1

**Comment by dvzrv** [comment]
@boronine Thanks! LGTM! :)

**Comment by hartwork** [comment]
> If either of you confirm that it looks good on your end too, I will release it as v5.0.1

I made the CI confirm that [your solution](https://github.com/hsluv/hsluv-python/commit/ec50039c7571ad288c23549bfec58f254626553c#diff-41d5a52589e0480be9c099d2bba7a8135b8b0d71bcbb8df3582a8df1c2295003R2) works and will not break unnoticed in a new pull request #31.

**Comment by hartwork** [comment]
Fixed by https://github.com/hsluv/hsluv-python/commit/ec50039c7571ad288c23549bfec58f254626553c#diff-41d5a52589e0480be9c099d2bba7a8135b8b0d71bcbb8df3582a8df1c2295003R2 , closing.
