### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by boronine** [hsluv/hsluv-python#32]
Originally suggested by @hartwork here: https://github.com/hsluv/hsluv-python/pull/30#issuecomment-781407034

I agree with this, but we should do it in the next version, e.g. v5.1.0 so that we can refer Python 2 users to v5.0.1.

**Comment by hartwork** [comment]
Do you want to go for a pull request or should I?

**Comment by boronine** [comment]
A PR would be great! I'm working on 5.0.1 release now

**Comment by hartwork** [comment]
Alright, let me see…

**Comment by boronine** [comment]
I forgot that I merged #33 yesterday, so the original plan in this issue fell through.. so now v5.0.2 is the new Python 3 only version and for Python 2 we will reference v5.0.0.

**Comment by hartwork** [comment]
That seems pretty okay to me. Are you worried about 5.0.0 being the last on Python 2?

**Comment by boronine** [comment]
Nope, the only downside is that there is no released version with both Python 2 support + LICENSE file. I don't think it's worth worrying about.
