### ISSUE TITLE
[5.0.1] Readme rendering broken at PyPI hsluv — release created with setuptools <38.6.0?

### ISSUE THREAD

**Issue by hartwork** [hsluv/hsluv-python#35]
Hi @boronine,

could it be that you ran `setup.py sdist` for hsluv 5.0.1 in an environment with setuptools [older than version 38.6.0](https://github.com/hsluv/hsluv-python/blob/0b5a04dbbe548bce4236c981110f23f787df1edd/setup.py#L30-L32)?
I'm asking because the markdown readme rending is broken at https://pypi.org/project/hsluv/ and my guess is that the setuptools used to create the release was too old to understand the [explicit markdown mimetime](https://github.com/hsluv/hsluv-python/blob/0b5a04dbbe548bce4236c981110f23f787df1edd/setup.py#L30-L32) that is needed for markdown to be rendered on PyPI. What do you think?

Best, Sebastian

PS: This is what I see on PyPI:
![hsluv_Screenshot_20210220_153518](https://user-images.githubusercontent.com/1577132/108599667-c99f1e80-7392-11eb-9e24-bca24f9db509.png)

**Comment by boronine** [comment]
Hi @hartwork, I saw that yesterday too. I am using this automation to publish: https://github.com/hsluv/hsluv/blob/master/default.nix#L332-L334

I just upgraded nixpkgs (and was forced to also upgrade Haxe), now testing!

**Comment by hartwork** [comment]
> Hi @hartwork, I saw that yesterday too. I am using this automation to publish: https://github.com/hsluv/hsluv/blob/master/default.nix#L332-L334

Is that nixpkgs of branch `master` i.e. file https://github.com/raboof/nixpkgs/blob/master/pkgs/development/python-modules/setuptools/default.nix ? I know NixOS to be rather bleeding edge but setuptools 41.2.0 is [~18 months old](https://github.com/pypa/setuptools/releases?after=v41.2.0) — I have 53.0.0 here, for comparison.


> I just upgraded nixpkgs (and was forced to also upgrade Haxe), now testing!

You could upload to the [testing instance of PyPI](https://packaging.python.org/guides/using-testpypi/), if you wanted to. (I recommend against ever *installing from it* for security reasons though.)

**Comment by hartwork** [comment]
PS: I saw you deleted release 5.0.1 on PyPI now. Please note that you cannot (and should not) re-upload different content under the same version and that removing releases from PyPI can easily break user builds — reverse dependencies —, e.g. everyone who was quick to bump their pinning to `hsluv==5.0.1` already using some automated bumping solution. I would totally understand if someone came here angry, just so you know.

**Comment by hartwork** [comment]
PPS: Any chance that `python` at https://github.com/hsluv/hsluv/blob/6b279ae16a29cdeebe4705c4a16e19fc2a6a8b7e/default.nix#L128 is actually Python 2.7? I'll shut up know, let me know what you'll find :smiley:

**Comment by boronine** [comment]
@hartwork yep just learned the hard way that I cannot reupload. PyPI test worked using upgraded nixpkgs automation: https://test.pypi.org/project/hsluv/

PyPI test automated here: https://github.com/hsluv/hsluv/blob/master/default.nix#L336-L338

The `python` binary wasn't an issue but I updated it to `python3` in master anyways.

Now going to publish v5.0.2 with fixed markdown

**Comment by boronine** [comment]
@hartwork hurray! https://pypi.org/project/hsluv/5.0.2/
@dvzrv this release should be package-able for you as well.

**Comment by hartwork** [comment]
> @hartwork yep just learned the hard way that I cannot reupload. PyPI test worked using upgraded nixpkgs automation: https://test.pypi.org/project/hsluv/

Was it setuptools that needed updating?


> PyPI test automated here: https://github.com/hsluv/hsluv/blob/master/default.nix#L336-L338

In see!

> The `python` binary wasn't an issue but I updated it to `python3` in master anyways.

Cool! :+1: 


> Now going to publish v5.0.2 with fixed markdown

Looks great, thank you! :tada:

**Comment by boronine** [comment]
> Was it setuptools that needed updating?

I believe so but I didn't actually look into the specific versions. I just know that our nixpkgs was pinned about 2 years old: https://github.com/NixOS/nixpkgs/commit/3ab38ef086947822fbe2cffea071e1c508811990

**Comment by hartwork** [comment]
> > Was it setuptools that needed updating?
> 
> I believe so but I didn't actually look into the specific versions. I just know that our nixpkgs was pinned about 2 years old: [NixOS/nixpkgs@3ab38ef](https://github.com/NixOS/nixpkgs/commit/3ab38ef086947822fbe2cffea071e1c508811990)

Then that's the answer:

```console
# git show 3ab38ef086947822fbe2cffea071e1c508811990:pkgs/development/python-modules/setuptools/default.nix | fgrep "version ="
  version = "38.4.0";
```

38.4.0 is older than the >=38.6.0 we need.

**Comment by boronine** [comment]
Oh nice one-liner!
