### ISSUE TITLE
Package is no longer on PyPI

### ISSUE THREAD

**Issue by damienrj** [hsluv/hsluv-python#36]
Currently hsluv is no longer on pypi, will it be uploaded again?

**Comment by hartwork** [comment]
@damienrj while Google cache still list the page URL https://pypi.org/project/hsluv/ gives 404 for me, too :scream: @boronine do you know what has happened to the PyPI package? I believe you are were the owner on PyPI?

**Comment by damienrj** [comment]
Pypi yanked a lot of packages in response to https://www.cyberkendra.com/2022/05/python-ctx-and-php-library-compromised.html I believe.

**Comment by hartwork** [comment]
@damienrj I was able to upload version 5.0.3 to PyPI under the same name "hsluv" just now. The content is the same as 5.0.2 plus two trivial commits:
- 56d97aa — Add note for Python 2 users, refs #32
- b628f92 — Bump version to v5.0.3

@boronine I hope that me uploading 5.0.3 now has your blessing. I felt that action was urgently needed and that there was even potential risk that *anyone* could upload and re-occupy name "hsluv" on PyPI — not sure —, so I thought we'd better be quick and first then, just in case. I would still like to learn how the package disappeared from PyPI, if you know anything about that.

PS: Uploading files for 5.0.2 was blocked by PyPI saying that the filename has already been used before, which makes some sense.

Best, Sebastian :beers:

**Comment by damienrj** [comment]
Great thanks, our builds are working again as well.

**Comment by boronine** [comment]
@hartwork thank you for your quick remedy! 🙏 5.0.3 is great and you can feel free to release without my blessing in the future! I sent you an email regarding this incident.
