### ISSUE TITLE
Current Travis CI is "dead", re-do with GitHub Actions?

### ISSUE THREAD

**Issue by hartwork** [hsluv/hsluv-python#37]
Hi @boronine 

I noticed at https://github.com/hsluv/hsluv-python/commits/master that the latest commit did not get CI coverage by Travis any more. I suggest we re-do CI with GitHub Actions, I could do the work if desired. What do you think?

Best, Sebastian

**Comment by boronine** [comment]
Hi @hartwork, it would be awesome! Actually a lot of our ports use Travis CI, I wanted to gradually move them over to GitHub Actions as we did with the main repo.
