### ISSUE TITLE
5.0.4: There is no Git tag for the release on PyPI

### ISSUE THREAD

**Issue by dvzrv** [hsluv/hsluv-python#44]
Hi! I package this project for Arch Linux.

We are now relying on upstream provided sources instead of PyPI: https://rfc.archlinux.page/0020-sources-for-python-packaging/

Unfortunately, for 5.0.4 on PyPI there is no related tag in this repository and I am unable to upgrade the package. Can you please add it? :)

**Comment by hartwork** [comment]
Hi @dvzrv, it seems like @boronine forgot about pushing a new tag when doing a release to PyPI. I have pushed a new Git tag `v5.0.4` pointing to the only candidate commit 50a60aa6357fd5f743e39d8e29b771a645a83b4a just now. I'll close the issue as fixed, thanks for taking it upstream :+1:

**Comment by boronine** [comment]
Thank you @hartwork!
