### ISSUE TITLE
rgb_to_huslp - saturation value error

### ISSUE THREAD

**Issue by ahmet-bradi** [hsluv/hsluv-python#6]
Something wrong with translate rgb to huslp. huslp must output H(0-360), S(0-100), L(0-100) but husl.rgb_to_huslp(0.6666666666666666, 0.3215686274509804, 0.7607843137254902) output 295.94701360615693, 204.03762706932616, 50.06910179946446

Channel saturation is wrong?

**Comment by Telemin** [comment]
Are you sure that the RGB co-ordinates you have chosen are within the huslp colorspace?  If not, then you cannot expect a valid huslp result.  The rgb_to_husl* functions are only designed to translate according the colormodel equations.  They do not attempt to coerce an invalid input to the nearest valid point in the husl colorspace.

**Comment by boronine** [comment]
@Telemin is right, the RGB color is outside of the HPLuv (formerly known as HUSLp) gamut.
